### ISSUE TITLE
NoMethodError undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by cobodo** [cobodo/mikutter-worldon#31]
```
NoMethodError undefined method `[]' for nil:NilClass
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:163:in `user_icon'
{MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:157:in `render_icon'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:152:in `render_user'
{MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:147:in `block in put_voter'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:145:in `each'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:145:in `put_voter'
{MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:76:in `block in render'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:72:in `save'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_voter.rb:72:in `render'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:29:in `block (3 levels) in render_parts'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:28:in `save'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:28:in `block (2 levels) in render_parts'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:27:in `each'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:27:in `block in render_parts'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:24:in `save'
{MIKUTTER_DIR}/core/mui/cairo_sub_parts_helper.rb:24:in `render_parts'
{MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
{MIKUTTER_DIR}/core/mui/cairo_miracle_painter.rb:381:in `render_to_context'
{MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
{MIKUTTER_DIR}/core/mui/cairo_miracle_painter.rb:350:in `gen_pixmap'
{MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
{MIKUTTER_DIR}/core/mui/cairo_miracle_painter.rb:356:in `gen_pixbuf'
{MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
{MIKUTTER_DIR}/core/mui/cairo_miracle_painter.rb:121:in `pixbuf'
{MIKUTTER_DIR}/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
{MIKUTTER_DIR}/core/mui/cairo_cell_renderer_message.rb:149:in `render_message'
{MIKUTTER_DIR}/core/mui/cairo_cell_renderer_message.rb:128:in `uri='
rbgobject.c:336:in `set_property'
rbgobject.c:336:in `set_value'
{MIKUTTER_DIR}/core/mui/gtk_tree_view_pretty_scroll.rb:23:in `block in initialize'
{MIKUTTER_DIR}/core/mui/gtk_extension.rb:35:in `block in safety_signal_connect'
{MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `main'
{MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `mainloop'
./mikutter.rb:68:in `boot!'
./mikutter.rb:104:in `<main>'
```

おそらく #25, #30 関連。

**Comment by cobodo** [comment]
acbfd84e272330c3c3cb62ac93013e458063b977 でnilを返すかもしれない場所を潰したがどうか。

**Comment by cobodo** [comment]
最近見ないから大丈夫っぽい
