### ISSUE TITLE
Pleromaのインスタンスを追加した際に相手のインスタンスに負荷をかけさせているような挙動を起こす

### ISSUE THREAD

**Issue by kazu0617** [cobodo/mikutter-worldon#86]
少し、というか大分特殊なのですが…
他のMastodonクライアントでもPleromaのインスタンスを追加した所正常に動くことが多かったため、試しにworldonプラグインを用いてPleromaインスタンスを追加した所、たしかに正常に追加され、投稿もできるのですが、Steamingの処理がうまく行ってないのか処理が大変なことになっていましたので報告します。  
検証環境としては以下の通りです。
- mikutter: 3.8.1
- 対象Pleromaインスタンス: heislandmine.mydns.jp (ログは [@6@heislandmine.mydns.jp](https://heislandmine.mydns.jp/users/12317) アカウントのものです)
- 対象worldonプラグイン: commit 07d6306820f37bff7d3d38c864d2dede77de0306

以上の環境で出てたログは以下の通りです。
```
notice: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:213:in `block (2 levels) in <top (required)>': SSE: connection open for worldon-heislandmine.mydns.jp-local
warning: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:224:in `block (2 levels) in <top (required)>': SSE: connection closed for worldon-heislandmine.mydns.jp-local
notice: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:213:in `block (2 levels) in <top (required)>': SSE: connection open for worldon-heislandmine.mydns.jp-local
warning: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:224:in `block (2 levels) in <top (required)>': SSE: connection closed for worldon-heislandmine.mydns.jp-local
notice: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:213:in `block (2 levels) in <top (required)>': SSE: connection open for worldon-6@heislandmine.mydns.jp-home
warning: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:224:in `block (2 levels) in <top (required)>': SSE: connection closed for worldon-6@heislandmine.mydns.jp-home
notice: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:213:in `block (2 levels) in <top (required)>': SSE: connection open for worldon-6@heislandmine.mydns.jp-home
warning: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:224:in `block (2 levels) in <top (required)>': SSE: connection closed for worldon-6@heislandmine.mydns.jp-home
notice: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:213:in `block (2 levels) in <top (required)>': SSE: connection open for worldon-heislandmine.mydns.jp-local
warning: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:224:in `block (2 levels) in <top (required)>': SSE: connection closed for worldon-heislandmine.mydns.jp-local
notice: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:213:in `block (2 levels) in <top (required)>': SSE: connection open for worldon-heislandmine.mydns.jp-local
warning: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:224:in `block (2 levels) in <top (required)>': SSE: connection closed for worldon-heislandmine.mydns.jp-local
notice: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:213:in `block (2 levels) in <top (required)>': SSE: connection open for worldon-6@heislandmine.mydns.jp-home
warning: /home/kazu0617/.mikutter/plugin/worldon/sse_stream.rb:224:in `block (2 levels) in <top (required)>': SSE: connection closed for worldon-6@heislandmine.mydns.jp-home
```

**Comment by cobodo** [comment]
Pleroma APIはMastodon互換を謳っていますが、実態としては、MastodonにあるはずのAPIがなかったり、同じエンドポイントでも対応しているパラメータに差があったりしていて、必ずしも互換ではありません。
こういった状況と、私自身Pleromaのアカウントを運用していないということから、Pleromaに対する特殊な対応を行うことはありません。
Pleromaに（も）対応するためのパッチがpull requestされ、それがMastodon側に影響しないものならmergeする可能性はありますが、私の方からはそういったものは書きません。

そういったわけでこのチケットはクローズします。
